version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_app
        container_name: laravel_app
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: mysql_container
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
        driver: local
